name: lava_car
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  device_preview: ^1.1.0
  dio: ^5.5.0+1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  http: ^1.2.1
  mask: ^1.0.5
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
