// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbmt5rfiGVdEsRboeja94plJFv6kDYpw8',
    appId: '1:532179527143:web:fa35aa9ff01b2d586a0942',
    messagingSenderId: '532179527143',
    projectId: 'lavacar-e3c4a',
    authDomain: 'lavacar-e3c4a.firebaseapp.com',
    storageBucket: 'lavacar-e3c4a.firebasestorage.app',
    measurementId: 'G-CCRRE9GZ5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZtxWEecaArfov8VMaHYeqBwsQs_-faO0',
    appId: '1:532179527143:android:8bf913ffe362bca86a0942',
    messagingSenderId: '532179527143',
    projectId: 'lavacar-e3c4a',
    storageBucket: 'lavacar-e3c4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq90Ec-8GBZRCKscQOwBtUQntmf2UletQ',
    appId: '1:532179527143:ios:86c23c1fc3f35d476a0942',
    messagingSenderId: '532179527143',
    projectId: 'lavacar-e3c4a',
    storageBucket: 'lavacar-e3c4a.firebasestorage.app',
    iosBundleId: 'com.example.lavaCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq90Ec-8GBZRCKscQOwBtUQntmf2UletQ',
    appId: '1:532179527143:ios:86c23c1fc3f35d476a0942',
    messagingSenderId: '532179527143',
    projectId: 'lavacar-e3c4a',
    storageBucket: 'lavacar-e3c4a.firebasestorage.app',
    iosBundleId: 'com.example.lavaCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAii0xKkc5WppdLDjp498RKV-_m8U4oKGE',
    appId: '1:532179527143:web:72acdaf9740a997c6a0942',
    messagingSenderId: '532179527143',
    projectId: 'lavacar-e3c4a',
    authDomain: 'lavacar-e3c4a.firebaseapp.com',
    storageBucket: 'lavacar-e3c4a.firebasestorage.app',
    measurementId: 'G-CXM7EB28NF',
  );

}