// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ9Xiwsqo0foEVo3nGL17ZYnopIyZ0xkE',
    appId: '1:564681181043:web:357a5c4368b34799192706',
    messagingSenderId: '564681181043',
    projectId: 'lavacar-c2646',
    authDomain: 'lavacar-c2646.firebaseapp.com',
    storageBucket: 'lavacar-c2646.firebasestorage.app',
    measurementId: 'G-8PQZ029B10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaO9uErhRSI6ppFogWjpa3A5gnfw7GzCQ',
    appId: '1:564681181043:android:cfc10b2cb0294b73192706',
    messagingSenderId: '564681181043',
    projectId: 'lavacar-c2646',
    storageBucket: 'lavacar-c2646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHSxg6U9Y6mMNHM4XoZUf-aT58jy08Lrc',
    appId: '1:564681181043:ios:d2e28f83df97b934192706',
    messagingSenderId: '564681181043',
    projectId: 'lavacar-c2646',
    storageBucket: 'lavacar-c2646.firebasestorage.app',
    iosBundleId: 'com.example.lavaCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHSxg6U9Y6mMNHM4XoZUf-aT58jy08Lrc',
    appId: '1:564681181043:ios:d2e28f83df97b934192706',
    messagingSenderId: '564681181043',
    projectId: 'lavacar-c2646',
    storageBucket: 'lavacar-c2646.firebasestorage.app',
    iosBundleId: 'com.example.lavaCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ9Xiwsqo0foEVo3nGL17ZYnopIyZ0xkE',
    appId: '1:564681181043:web:1e27e2ec3fb0de21192706',
    messagingSenderId: '564681181043',
    projectId: 'lavacar-c2646',
    authDomain: 'lavacar-c2646.firebaseapp.com',
    storageBucket: 'lavacar-c2646.firebasestorage.app',
    measurementId: 'G-JD1TQS7JTC',
  );

}